# Generated by Django 2.2.6 on 2019-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('support_email', models.CharField(max_length=100)),
                ('stripe_secret_key', models.CharField(max_length=250)),
                ('stripe_publishable_key', models.CharField(max_length=250)),
                ('coinbase_api_Key', models.CharField(max_length=250)),
                ('coinbase_scrate_key', models.CharField(max_length=250)),
            ],
        ),
    ]
