# Generated by Django 2.2.6 on 2019-11-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(blank=True, max_length=20)),
                ('mobileNumber', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('address_one', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('about_you', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
